### ISSUE TITLE
Domani tened over

### ISSUE THREAD

**Issue by ic32k** [JulienBeg/U-EM#1]
Is there any other site where we can download the DPA files? Looks like the domain expired and it is no longer available to download

**Comment by JulienBeg** [comment]
It seems that the website from DPA contest is down indeed. I am not aware of any alternative to obtain the traces. I guess the easiest would be to contact the organizer of the DPA contest. I can try to ask them.

**Comment by JulienBeg** [comment]
I do not remember all the details of this repo but I believe you can use the PoIs that I extracted in the data folder though to run the code and replicate the results.  I do not think it is necessary to download the full traces from the DPA contest. 

Otherwise I suggest you use a more recent dataset such as SMAEsh https://smaesh-challenge.simple-crypto.org/ or ASCAD https://github.com/ANSSI-FR/ASCAD for your project.

**Comment by JulienBeg** [comment]
The old DPA contest url has been bought by a Phisher before it was renewed. This old url should not be used anymore. 

The new url for the dpa contest is: https://dpacontest.telecom-paris.fr

(The old url is still referenced  so the new url does nor appear in your favorite search engine. Copy paste directly the url).

**Comment by ic32k** [comment]
Thank you very much!!!
